# Generated by Django 5.2.1 on 2025-05-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=8, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('required_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
