# Generated by Django 5.2.1 on 2025-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
