# Generated by Django 5.2.1 on 2025-05-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_bloodrequest_is_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
    ]
